name: build

on: push

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: docker/Dockerfile
          push: false

      - run: echo ${{ steps.docker_build.outputs.digest }}
