name: publish

on:
  release:
    types:
      - published

jobs:
  push:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          case "${GITHUB_REF}" in
            refs/tags/v[0-9]*)
              version="${GITHUB_REF#refs/tags/v}"
              ;;
            *)
          esac
          echo "VERSION=${version}" >> ${GITHUB_ENV}

      - uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            snsinfu/test-r9zhesnz:latest
            snsinfu/test-r9zhesnz:${{ env.VERSION }}
          push: true
