name: publish

on:
  release:
    types:
      - published

jobs:
  push:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set metadata
        run: |
          version="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=${version}" >> ${GITHUB_ENV}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.VERSION }}
          push: true

      # Docker Hub API does not support token authorization yet!
      # https://github.com/peter-evans/dockerhub-description/issues/10
      # https://github.com/docker/hub-feedback/issues/1914
#     - uses: peter-evans/dockerhub-description@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#         repository: ${{ secrets.DOCKERHUB_REPOSITORY }}

      # This does not work either.
#     - name: update docker hub long description
#       run: .github/workflows/publish_readme.sh docker/README.md
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#         repository: ${{ env.DOCKERHUB_REPOSITORY }}
